trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    displayName: Checkout source
    persistCredentials: true
    fetchDepth: 0

  - script: |
      git config user.email "azure-pipeline@sugarfeet.com"
      git config user.name "Azure Pipeline"
      git remote add github https://$(GITHUB_TOKEN)@github.com/Pappas313/SugarFeet.git
      git push github HEAD:main --force
    displayName: Mirror to GitHub
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
